from flask import Flask, render_template, request
import cv2
import numpy as np
from tensorflow.keras.models import load_model

app = Flask(__name__)

model = load_model("model_resnet_300.h5")

# Dictionary containing descriptions and recommendations for each class
class_info = {
    0: {
        "description": "Actinic keratosis Actinic keratoses are scaly spots or patches on the top layer of skin. With time they may become hard with a wartlike surface. Also known as a solar keratosis, an actinic keratosis grows slowly and usually first appears in people over 40. You can reduce your risk of this skin condition by minimizing your sun exposure and protecting your skin from ultraviolet (UV) rays. Left untreated, the risk of actinic keratoses turning into a type of skin cancer called squamous cell carcinoma is about 5% to 10%.",
        "Symptoms" :"Actinic keratoses vary in appearance. Symptoms include:\n"
               "Rough, dry or scaly patch of skin, usually less than 1 inch (2.5 centimeters) in diameter.\n"
               "Flat to slightly raised patch or bump on the top layer of skin.\n"
               "In some cases, a hard, wartlike surface.\n"
               "Color variations, including pink, red or brown.\n"
               "Itching, burning, bleeding or crusting.\n"
               "New patches or bumps on sun-exposed areas of the head, neck, hands and forearms.",
        "When to see a doctor" :"It can be difficult to distinguish between noncancerous spots and cancerous ones. So it's best to have new skin changes evaluated by a health care provider — especially if a scaly spot or patch persists, grows or bleeds",
        "recommendation": "Sun safety helps prevent actinic keratoses. Take these steps to protect your skin from the sun:\n\n"
                 "Limit your time in the sun. Especially avoid time in the sun between 10 a.m. and 2 p.m. And avoid staying in the sun so long that you get a sunburn or a suntan.\n"
                 "Use sunscreen. Before spending time outdoors, apply a broad-spectrum water-resistant sunscreen with a sun protection factor (SPF) of at least 30, as the American Academy of Dermatology recommends. Do this even on cloudy days.\n\n"
                 "Use sunscreen on all exposed skin. And use lip balm with sunscreen on your lips. Apply sunscreen at least 15 minutes before going outside and reapply it every two hours — or more often if you're swimming or sweating.\n\n"
                 "Sunscreen is not recommended for babies under 6 months. Rather, keep them out of the sun if possible. Or protect them with shade, hats, and clothing that covers the arms and legs.\n\n"
                 "Cover up. For extra protection from the sun, wear tightly woven clothing that covers your arms and legs. Also wear a broad-brimmed hat. This provides more protection than does a baseball cap or golf visor.\n\n"
                 "Avoid tanning beds. The UV exposure from a tanning bed can cause just as much skin damage as a tan from the sun.\n\n"
                 "Check your skin regularly and report changes to your health care provider. Examine your skin regularly, looking for the development of new skin growths or changes in existing moles, freckles, bumps and birthmarks. With the help of mirrors, check your face, neck, ears and scalp. Examine the tops and undersides of your arms and hands."
    },
    1: {
        "description": "Basal cell carcinoma on white skin Basal cell carcinoma is a type of skin cancer that most often develops on areas of skin exposed to the sun, such as the face. On white skin, basal cell carcinoma often looks like a bump that's skin-colored or pink. Basal cell carcinoma on brown skin Basal cell carcinoma is a type of skin cancer that most often develops on areas of skin exposed to the sun, such as the face. On brown and Black skin, basal cell carcinoma often looks like a bump that's brown or glossy black and has a rolled border.",
        "Symptoms" : "Symptoms Basal cell carcinoma usually develops on sun-exposed parts of your body, especially your head and neck. Less often, basal cell carcinoma can develop on parts of your body usually protected from the sun, such as the genitals. Basal cell carcinoma appears as a change in the skin, such as a growth or a sore that won't heal. These changes in the skin (lesions) usually have one of the following characteristics: A shiny, skin-colored bump that's translucent, meaning you can see a bit through the surface. The bump can look pearly white or pink on white skin. On brown and Black skin, the bump often looks brown or glossy black. Tiny blood vessels might be visible, though they may be difficult to see on brown and Black skin. The bump may bleed and scab over. A brown, black or blue lesion — or a lesion with dark spots — with a slightly raised, translucent border. A flat, scaly patch with a raised edge. Over time, these patches can grow quite large. A white, waxy, scar-like lesion without a clearly defined border.",
        "When to see a doctor":"Make an appointment with your health care provider if you observe changes in the appearance of your skin, such as a new growth, a change in a previous growth or a recurring sore.",
        "recommendation": "To reduce your risk of basal cell carcinoma you can: Avoid the sun during the middle of the day. In many places, the sun's rays are strongest between about 10 a.m. and 4 p.m. Schedule outdoor activities for other times of the day, even during winter or when the sky is cloudy. Wear sunscreen year-round. Use a broad-spectrum sunscreen with an SPF of at least 30, even on cloudy days. Apply sunscreen generously, and reapply every two hours — or more often if you're swimming or perspiring. Wear protective clothing. Cover your skin with dark, tightly woven clothing that covers your arms and legs, and a broad-brimmed hat, which provides more protection than does a baseball cap or visor. Some companies also sell protective clothing. A dermatologist can recommend an appropriate brand. Don't forget sunglasses. Look for those that block both types of UV radiation — ultraviolet A (UVA) and ultraviolet B (UVB) rays. Avoid tanning beds. Tanning beds emit UV rays and can increase your risk of skin cancer. Check your skin regularly and report changes to your doctor. Examine your skin often for new skin growths or changes in existing moles, freckles, bumps and birthmarks. With the help of mirrors, check your face, neck, ears and scalp. Examine your chest and trunk and the tops and undersides of your arms and hands. Examine both the front and the back of your legs and your feet, including the soles and the spaces between your toes. Also check your genital area and between your buttocks."

    },
    2: {
        "description": "Dermatofibrosarcoma protuberans (DFSP) is a rare type of skin cancer. It starts in connective tissue cells in the middle layer of the skin (dermis). Dermatofibrosarcoma protuberans might look like a pimple or feel like a rough patch of skin at first. As it grows, lumps of tissue (protuberans) may form near the surface of the skin. This skin cancer often forms on the arms, legs and trunk. Dermatofibrosarcoma protuberans grows slowly and rarely spreads beyond the skin.",
        "Symptoms" :"Initially may appear as a pimple or a rough patch of skin As it grows, lumps of tissue (protuberans) may form near the surface of the skin Often found on the arms, legs, and trunk Usually grows slowly and rarely spreads beyond the skin",
        "When to see a doctor" :"Dermatofibrosarcoma protuberans (DFSP) typically involves noticing any new or changing skin lesions, especially if they resemble a pimple or rough patch of skin that persists or grows larger. Early detection and treatment can improve outcomes. If you notice any concerning skin changes, it's important to schedule an appointment with a healthcare provider for evaluation and further management.",
        "recommendation": "Dermatofibrosarcoma protuberans treatment typically involves surgery to remove the cancer. Other treatments may be used to kill cancer cells that might remain after surgery. Treatment options may include: Surgery to remove the cancer. Your health care provider may recommend a procedure to remove the cancer and some of the healthy tissue around it. This makes it more likely that all the cancer cells are removed. Mohs surgery. Mohs surgery is a type of surgery that involves cutting away thin layers of cancer-containing skin until only cancer-free tissue is left. After each layer of skin is removed, it's examined for signs of cancer. The process keeps going until there are no signs of cancer. Mohs surgery may be helpful for treating larger cancers. Dermatofibrosarcoma protuberans tends to grow in an irregular shape that makes it hard to remove completely. Radiation therapy. Radiation therapy uses powerful energy beams, such as X-rays and protons, to kill cancer cells. Your provider may recommend radiation therapy if all the cancer couldn't be removed during surgery. Targeted therapy. Targeted therapy drugs attack specific chemicals present in cancer cells. By blocking these chemicals, targeted drug treatments cause cancer cells to die. Some people with dermatofibrosarcoma protuberans have cancer cells that produce an excess protein. A drug called imatinib (Gleevec) can target those cells and cause them to die. Your provider may recommend this treatment if your cancer returns after surgery. Clinical trials. Clinical trials to test new treatments may be an option. Ask your provider whether you're eligible to participate in a clinical trial."

    },
    3: {
        "description": "Melanoma is a kind of skin cancer that starts in the melanocytes. Melanocytes are cells that make the pigment that gives skin its color. The pigment is called melanin. Melanoma typically starts on skin that's often exposed to the sun. This includes the skin on the arms, back, face and legs. Melanoma also can form in the eyes. Rarely, it can happen inside the body, such as in the nose or throat. The exact cause of all melanomas isn't clear. Most melanomas are caused by exposure to ultraviolet light. Ultraviolet light, also called UV light, comes from sunlight or tanning lamps and beds. Limiting exposure to UV light can help reduce the risk of melanoma.",
        "Symptoms" : "The first melanoma signs and symptoms often are: A change in an existing mole. The development of a new pigmented or unusual-looking growth on the skin. Melanoma doesn't always begin as a mole. It also can happen on otherwise healthy skin. Melanomas symptoms can happen anywhere on the body. Melanomas most often develop in areas that have had exposure to the sun. This includes the arms, back, face and legs. Melanomas also can happen in areas that aren't as exposed to the sun. This includes the soles of the feet, palms of the hands and fingernail beds. Melanoma also can happen inside the body. These hidden melanomas are more common in people with brown or Black skin.",
        "When to see a doctor" :"Make an appointment with your doctor or other healthcare professional if you notice any skin changes that worry you.",
        "recommendation": "You can reduce your risk of melanoma and other types of skin cancer if you: Avoid tanning lamps and beds. Tanning lamps and beds give off ultraviolet light, also called UV light. Exposure to this kind of light can increase your risk of skin cancer. Avoid the sun during the middle of the day. For many people in North America, the sun's rays are strongest between about 10 a.m. and 4 p.m. Schedule outdoor activities for other times of the day, even in winter or when the sky is cloudy. Become familiar with your skin so that you'll notice changes. Check your skin often for new skin growths. Look for changes in existing moles, freckles, bumps and birthmarks. With the help of mirrors, check your face, neck, ears and scalp. Look at your chest and trunk and the tops and undersides of your arms and hands. Check both the front and back of your legs and your feet, including the soles and the spaces between your toes. Also check your genital area and between your buttocks. Wear protective clothing. When you go outside during the day, wear clothes that help protect your skin from the sun's rays. Cover your skin with dark, tightly woven clothing that covers your arms and legs. Wear a broad-brimmed hat, which provides more protection than does a baseball cap or visor. Some companies also sell protective clothing. A dermatologist can recommend an appropriate brand. Don't forget sunglasses. Look for those that block both types of UV light that come from the sun, called UVA and UVB. Wear sunscreen year-round. Use a broad-spectrum sunscreen with an SPF of at least 30, even on cloudy days. Apply sunscreen generously. Reapply every two hours, or more often if you're swimming or sweating."

    },
    4: {
        "description": "Nevus is a common, benign growth of melanocytes, also known as a mole.",
        "Symptoms" :"Presence of a pigmented spot on the skin, varying in color from brown to black. Usually round or oval in shape. Can be flat or raised. Typically appear during childhood or adolescence, but can develop at any age.",
        "When to see a doctor" :"You should see a doctor if you notice any of the following changes in a mole: Change in size, shape, or color; Irregular borders; Bleeding, itching, or pain; Ulceration or crusting; Rapid growth",
        "recommendation": "Avoid excessive sun exposure, especially during peak hours. Wear sunscreen with SPF 30 or higher when outdoors. Wear protective clothing, such as wide-brimmed hats and long-sleeved shirts. Perform regular skin self-exams to monitor for changes in moles. Seek medical evaluation for any suspicious or changing moles. Regular skin checks by a dermatologist are recommended, especially for individuals with a history of skin cancer or a large number of moles."

    },
    5: {
        "description": "A seborrheic keratosis is a common noncancerous (benign) skin growth. People tend to get more of them as they get older. Seborrheic keratoses are usually brown, black or light tan. The growths (lesions) look waxy or scaly and slightly raised. They appear gradually, usually on the face, neck, chest or back. Seborrheic keratoses on the back Seborrheic keratoses are very common on the back. They appear as waxy light tan, brown or black growths that look as if they were dripped onto the skin by a candle. Some can grow large, more than 1 inch (2.5 centimeters) across. Seborrheic keratoses are harmless and not contagious. They don't need treatment, but you may decide to have them removed if they become irritated by clothing or you don't like how they look.",
        "Symptoms" : "A seborrheic keratosis grows gradually. Signs and symptoms might include: A round or oval-shaped waxy or rough bump, typically on the face, chest, a shoulder or the back. A flat growth or a slightly raised bump with a scaly surface, with a characteristic 'pasted on' look. Varied size, from very small to more than 1 inch (2.5 centimeters) across. Varied number, ranging from a single growth to multiple growths. Very small growths clustered around the eyes or elsewhere on the face, sometimes called flesh moles or dermatosis papulosa nigra, common on Black or brown skin. Varied in color, ranging from light tan to brown or black. Itchiness.",
        "When to see a doctor":"See your doctor if the appearance of the growth bothers you or if it gets irritated or bleeds when your clothing rubs against it. Also see your doctor if you notice suspicious changes in your skin, such as sores or growths that grow rapidly, bleed and don't heal. These could be signs of skin cancer.",
        "recommendation": "Seborrheic keratosis is a benign skin growth and there are no specific prevention measures to completely avoid them. However, some general skincare practices may help minimize their occurrence or reduce the risk of irritation: 1. Sun Protection: Protect your skin from excessive sun exposure by wearing sunscreen with SPF 30 or higher, seeking shade during peak sun hours, and wearing protective clothing such as wide-brimmed hats and long-sleeved shirts. 2. Moisturize: Keeping your skin well-hydrated with regular moisturizing may help maintain skin health and potentially reduce the development of seborrheic keratoses. 3. Regular Skin Checks: Perform regular self-examinations of your skin to monitor for any new or changing growths. Promptly report any concerning changes to your healthcare provider. 4. Healthy Lifestyle: Maintain a healthy lifestyle with a balanced diet, regular exercise, and adequate hydration to support overall skin health. 5. Medical Evaluation: If you notice any unusual growths or changes in your skin, consult a dermatologist for proper evaluation and diagnosis. Early detection and treatment of any suspicious lesions can help prevent complications or discomfort. While these practices may not entirely prevent seborrheic keratoses, they can contribute to overall skin health and potentially reduce the risk of irritation or discomfort associated with these growths."
    },
    6: {
       
        "description": "A seborrheic keratosis is a common noncancerous (benign) skin growth. People tend to get more of them as they get older. Seborrheic keratoses are usually brown, black or light tan. The growths (lesions) look waxy or scaly and slightly raised. They appear gradually, usually on the face, neck, chest or back. Seborrheic keratoses on the back Seborrheic keratoses are very common on the back. They appear as waxy light tan, brown or black growths that look as if they were dripped onto the skin by a candle. Some can grow large, more than 1 inch (2.5 centimeters) across. Seborrheic keratoses are harmless and not contagious. They don't need treatment, but you may decide to have them removed if they become irritated by clothing or you don't like how they look.",
        "Symptoms" : "A seborrheic keratosis grows gradually. Signs and symptoms might include: A round or oval-shaped waxy or rough bump, typically on the face, chest, a shoulder or the back. A flat growth or a slightly raised bump with a scaly surface, with a characteristic 'pasted on' look. Varied size, from very small to more than 1 inch (2.5 centimeters) across. Varied number, ranging from a single growth to multiple growths. Very small growths clustered around the eyes or elsewhere on the face, sometimes called flesh moles or dermatosis papulosa nigra, common on Black or brown skin. Varied in color, ranging from light tan to brown or black. Itchiness.",
        "When to see a doctor":"See your doctor if the appearance of the growth bothers you or if it gets irritated or bleeds when your clothing rubs against it. Also see your doctor if you notice suspicious changes in your skin, such as sores or growths that grow rapidly, bleed and don't heal. These could be signs of skin cancer.",
        "recommendation": "Seborrheic keratosis is a benign skin growth and there are no specific prevention measures to completely avoid them. However, some general skincare practices may help minimize their occurrence or reduce the risk of irritation: 1. Sun Protection: Protect your skin from excessive sun exposure by wearing sunscreen with SPF 30 or higher, seeking shade during peak sun hours, and wearing protective clothing such as wide-brimmed hats and long-sleeved shirts. 2. Moisturize: Keeping your skin well-hydrated with regular moisturizing may help maintain skin health and potentially reduce the development of seborrheic keratoses. 3. Regular Skin Checks: Perform regular self-examinations of your skin to monitor for any new or changing growths. Promptly report any concerning changes to your healthcare provider. 4. Healthy Lifestyle: Maintain a healthy lifestyle with a balanced diet, regular exercise, and adequate hydration to support overall skin health. 5. Medical Evaluation: If you notice any unusual growths or changes in your skin, consult a dermatologist for proper evaluation and diagnosis. Early detection and treatment of any suspicious lesions can help prevent complications or discomfort. While these practices may not entirely prevent seborrheic keratoses, they can contribute to overall skin health and potentially reduce the risk of irritation or discomfort associated with these growths."
    },
    7: {
        "description":"Squamous cell carcinoma of the skin is a type of cancer that starts as a growth of cells on the skin. It starts in cells called squamous cells. The squamous cells make up the middle and outer layers of the skin. Squamous cell carcinoma is a common type of skin cancer. Squamous cell carcinoma of the skin is usually not life-threatening. But if it's not treated, squamous cell carcinoma of the skin can grow large or spread to other parts of the body. The growth of the cancer can cause serious complications. Most squamous cell carcinomas of the skin are caused by too much ultraviolet (UV) radiation. UV radiation comes either from sunlight or from tanning beds or lamps. Protecting your skin from UV light can help reduce the risk of squamous cell carcinoma of the skin and other forms of skin cancer.",
        "Symptoms" : "Squamous cell carcinoma of the skin most often occurs on sun-exposed skin. This includes the scalp, the backs of the hands, the ears or the lips. But it can occur anywhere on the body. It can even occur inside the mouth, on the bottoms of the feet or on the genitals. When squamous cell carcinoma of the skin happens in people with Black and brown skin, it tends to happen in places that aren't exposed to the sun. Symptoms of squamous cell carcinoma of the skin include: A firm bump on the skin, called a nodule. The nodule might be the same color as the skin, or it might look different. It can look pink, red, black or brown, depending on skin color. A flat sore with a scaly crust. A new sore or raised area on an old scar or sore. A rough, scaly patch on the lip that may become an open sore. A sore or rough patch inside the mouth. A raised patch or wartlike sore on or in the anus or on the genitals.",
        "When to see a doctor": "Make an appointment with a health care professional for a sore or scab that doesn't heal in about two months or a flat patch of scaly skin that won't go away.",
        "recommendation": "Most squamous cell carcinomas of the skin can be prevented. To protect yourself: Stay out of the sun during the middle of the day. For much of North America, the sun's rays are strongest between about 10 a.m. and 3 p.m. Plan outdoor activities at other times of the day, even during winter or when the sky is cloudy. When outside, stay in shade as much as possible. Wear sunscreen year-round. Use a broad-spectrum sunscreen with an SPF of at least 30, even on cloudy days. Apply sunscreen generously. Apply again every two hours, or more often if you're swimming or sweating. Wear protective clothing. Wear dark, tightly woven clothes that cover arms and legs. Wear a wide-brimmed hat that shades your face and ears. Don't forget sunglasses. Look for those that block both types of UV radiation, UVA and UVB rays. Don't use tanning beds. The lights in tanning beds give off UV radiation. Using tanning beds increases the risk of skin cancer. Check your skin often and report changes to your health care team. Look at your skin often for new growths. Look for changes in moles, freckles, bumps and birthmarks. Use mirrors to check your face, neck, ears and scalp. Look at your chest and trunk and the tops and undersides of your arms and hands. Look at the front and back of your legs and your feet. Look at the bottom of the feet and the spaces between your toes. Also check your genital area and between your buttocks."
    },
    8: {
        "description": "Vascular lesions are abnormal clusters of blood vessels that may appear on or under the skin. They can vary in size, color, and shape. Vascular lesions can be classified into different types, such as hemangiomas, port-wine stains, and spider veins.",
        "Symptoms" : "Symptoms of vascular lesions may include red, purple, or blue discoloration on the skin, raised or flat areas on the skin, pain or tenderness in the affected area, and bleeding or bruising.",
        "When to see a doctor":"If you notice any new or changing vascular lesions on your skin, it's important to consult a healthcare professional. Additionally, if you experience any pain, discomfort, or bleeding associated with vascular lesions, seek medical attention promptly.",
        "recommendation": "While some vascular lesions are present from birth and cannot be prevented, there are steps you can take to reduce your risk of developing certain types of vascular lesions: Protect your skin from excessive sun exposure to prevent the development of certain types of vascular lesions, such as spider veins. Practice good skincare habits, including moisturizing regularly and avoiding harsh chemicals or irritants that could damage the skin. Maintain a healthy lifestyle, including eating a balanced diet, exercising regularly, and avoiding smoking, which can contribute to vascular health. If you have a family history of vascular lesions or other vascular conditions, discuss preventive measures with your healthcare provider."
    }
}

# List of class names
labels = ['actinic keratosis', 'basal cell carcinoma', 'dermatofibroma', 'melanoma', 'nevus',
          'seborrheic keratosis', 'seborrheic keratosis', 'squamous cell carcinoma', 'vascular lesion']


@app.route('/')
def index():
    return render_template("index.html", data="hey")


@app.route("/prediction", methods=["POST"])
def prediction():
    img = request.files['img']
    img.save("static\\img.jpg")

    image = cv2.imread("static\\img.jpg")
    image = cv2.resize(image, (100, 100))

    x = np.expand_dims(image, axis=0)

    result = model.predict(x)
    
    result = (result * 100).astype('int')
    p = list((result * 100).astype('int'))
    pp = list(p[0])
    index = pp.index(max(pp))
    pred = index

    description = class_info[pred]["description"]
    recommendation = class_info[pred]["recommendation"]
    Symptoms = class_info[pred]["Symptoms"]
    return render_template("prediction.html", data=labels[pred], description=description, recommendation=recommendation,image_path="static/img.jpg",Symptoms=Symptoms)

if __name__ == "__main__":
    app.run(debug=True)
